export const depressao = [
  { 
    question: "Perdeu o interesse em atividades que te davam prazer?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Você prefere ficar deitado e sem fazer nada?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Gostava de frequentar ambientes sociais e agora evita?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Gosta de sair com seus amigos?", 
    answers: ["Sim", "Não"],
    weight: [0, 1],
  },
  { question: "Você tem um sentimento persistente de tristeza?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Esse sentimento de tristeza tem um motivo?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Tem sentimento de desesperança, inutilidade ou desamparo?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Sente dificuldade para se concentrar ou ter atenção?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Sente-se cansado com mais frequência?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Chora frequentemente e sem motivo?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Todas esses sentimentos e situações descritos acima atrapalham sua vida no dia a dia?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Pensa muito em morte ou em suicídio?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
]