export const diabetes = [
  { 
    question: "Você ou alguém da sua família já foi diagnosticada com diabetes gestacional?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Você ou alguém da sua família já foi diagnosticado(a) com pré-diabetes?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Você pratica atividade física regularmente?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Você possui sobrepeso?", 
    answers: ["Sim", "Não"],
    weight: [0, 1],
  },
  { question: "Alguém na sua família possui sobrepeso ou obesidade?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Alguém na sua família já foi diagnosticado com Diabetes Mellitus tipo 2?", 
    answers: ["Sim", "Não"],
    weight: [1, 0],
  },
  { question: "Dentro dos últimos 3 meses, você experienciou algum dos sintomas abaixo? Por favor, selecione-os.", 
    answers: ["Visão turva", "Fadiga", "Disfunção erétil", "Candidíase", "Infecção urinária", "Aumento de micção", "Aumento de sede", "Aumento de peso", "Perda de peso"],
    weight: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    type: "multiple",
  },
]